### ISSUE TITLE
Reentrancy

### ISSUE THREAD

**Issue by TheOpenFinanceProject** [MaxMustermann2/harmony-staking-precompiles#2]
I don't see any reentrancy failsafe.
Since you guys are sending native one tokens
Adding this to your tests is a good idea.
Just passing through and haven't tested anything.
Just popped in my mind.

**Comment by TheOpenFinanceProject** [comment]
saw only EOA as a test... making it harder but not impossible ?

**Comment by MaxMustermann2** [comment]
None of the contracts in this library send out native one tokens or HRC-20 tokens. Therefore, a reentrancy guard is not needed.

Please remember that `StakingPrecompiles.sol` is meant to serve as a smart contract staking library, while `StakingContract.sol` inherits the library and is solely used to demonstrate on a (modified) Harmony node that the precompiles work.
